name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: print Hello, world!
    - name: Run a multi-line script
      run: |
        print Add other actions to build,
        print test, and deploy your project.
